dataset_path: 'AnnotatedData'
sub_folder_list: [
  'U0_E0_1_sitting_1o3_none_0',
  'U0_E0_1_sitting_1o3_none_1',
  'U0_E0_1_standing_1o3_none_0',
  'U0_E0_1_walking_0o7_OLBP-0_0',
  'U0_E0_1_walking_0o7_OLBP-0_2',
  'U0_E0_1_standing_1o3_none_2',
  'U0_E0_1_walking_0o7_OLBP-20_0',
  'U0_E0_1_lying_1o3_none_0',
  'U0_E0_1_walking_0o7_OLBP-60_1',
  'U0_E0_1_walking_0o7_OLBP-60_0',
  'U0_E0_1_walking_1o3_none_0',
  'U0_E0_1_walking_1o3_none_1',
  'U0_E11_1_walking_1o3_none_0',
  'U0_E11_1_walking_1o3_none_2',
  'U0_E11_1_walking_1o3_none_4',
  'U0_E11_1_walking_1o3_none_3',

  'U0_E2_1_sitting_1o3_none_0',
  'U0_E2_1_walking_1o3_none_0',
  'U0_E3_1_standing_0o3_DH_0',
  'U0_E3_1_standing_0o7_DH_0',
  'U0_E3_1_standing_1o4_DH_0',
  'U0_E3_1_walking_0o3_DH_2',
  'U0_E3_1_walking_1o0_DH_0',
  'U0_E3_1_walking_1o0_DH_1',
  'U0_E0_1_lying_1o3_none_1',     
  'U0_E3_1_walking_1o4_DH_0',
  'U0_E3_1_walking_1o4_DH_1',
  'U1_E0_1_sitting_1o3_none_1',
  'U1_E0_1_sitting_1o3_none_0',
  'U10_E2_1_walking_1o3_none_2',
  'U10_E2_1_walking_1o3_none_1',
  'U10_E2_1_walking_1o3_none_0',
  'U1_E0_1_sitting_1o3_none_2',
  'U1_E0_1_sitting_1o3_none_3',
  'U1_E0_1_standing_1o3_none_0',
  'U1_E0_1_sitting_1o3_none_4',
  'U1_E0_1_standing_1o3_none_1',
  'U1_E0_1_walking_1o3_none_0',
  'U1_E0_1_walking_1o3_none_1',
  'U1_E0_1_walking_1o3_none_2',
  'U1_E0_1_walking_1o3_none_7',
  'U1_E11_1_walking_0o8_none_0',
  'U1_E11_1_walking_0o8_none_1',
  'U1_E11_1_walking_0o8_none_2',
  'U1_E11_1_walking_0o8_none_3',
  'U1_E11_1_walking_0o8_none_4',

  'U1_E2_1_sitting_1o3_none_0',
  'U1_E2_1_standing_1o3_none_0',
  'U2_E0_1_lying_1o3_none_3',
  'U2_E0_1_sitting_1o3_none_0',
  'U2_E0_1_sitting_1o3_none_3',
  'U2_E0_1_standing_1o3_none_0',
  'U2_E0_1_standing_1o3_none_1',
  'U2_E0_1_standing_1o3_none_2',
  'U2_E0_1_standing_1o3_none_3',
  'U2_E0_1_walking_1o3_none_0',
  'U2_E0_1_walking_1o3_none_1',
  'U2_E0_1_walking_1o3_none_6',
  'U2_E11_1_walking_0o8_none_0',
  'U2_E11_1_walking_0o8_none_1',
  'U2_E11_1_walking_0o8_none_2',
  'U2_E11_1_walking_0o8_none_3',
  'U2_E11_1_walking_1o3_none_4',

  'U2_E2_1_walking_1o3_none_2',
  'U3_E0_1_walking_1o3_none_0',
  'U3_E0_1_walking_1o3_none_1',
  'U3_E0_1_walking_1o3_none_2',
  'U6_E0_1_sitting_1o3_none_2',
  'U7_E2_1_sitting_1o3_none_2',
  'U7_E2_1_walking_1o3_none_0',
  'U7_E2_1_walking_1o3_none_1',
  'U9_E2_1_sitting_1o3_none_0',
  'U9_E2_1_sitting_1o3_none_1',
  'U9_E2_1_sitting_1o3_none_2',
  'U9_E2_1_walking_1o3_none_1',
  'U9_E2_1_sitting_1o3_none_4',
  'U9_E2_1_walking_1o3_none_2',
  'U9_E2_1_walking_1o3_none_4',


  'U0_E11_1_walking_1o3_OLBP-0_0',
  'U0_E11_1_walking_1o3_OLBP-20_0',
  'U0_E11_1_walking_1o3_OLBP-20_1',
  'U0_E11_1_walking_1o3_OLBP-40_0',
  'U0_E11_1_walking_1o3_OLBP-40_1',
  'U0_E11_1_walking_1o3_OLBP-40_4',
  'U0_E11_1_walking_1o3_OLBP-60_0',
  'U0_E11_1_walking_1o3_OLBP-60_1',
  'U0_E11_1_walking_1o3_OLBP-60_2',
  'U0_E11_1_walking_1o3_OLBP-80_0',
  'U0_E11_1_walking_1o3_OLBP-80_1',
  'U0_E11_1_walking_1o3_OLBP-80_2',

  'U0_E3_1_walking_1o0_UO0_0',
  'U0_E3_1_walking_1o0_UO0_1',
  'U0_E3_1_walking_1o0_UO120_0',
  'U0_E3_1_walking_1o0_UO120_1',
  'U0_E3_1_walking_1o0_UO150_0',
  'U0_E3_1_walking_1o0_UO150_1',
  'U0_E3_1_walking_1o0_UO180_0',
  'U0_E3_1_walking_1o0_UO180_1',
  'U0_E3_1_walking_1o0_UO30_0',
  'U0_E3_1_walking_1o0_UO30_1',
  'U0_E3_1_walking_1o0_UO60_0',
  'U0_E3_1_walking_1o0_UO60_1',
  'U0_E3_1_walking_1o0_UO90_0',
  'U0_E3_1_walking_1o0_UO90_1',
  'U1_E11_1_standing_1o3_UO0_0',
  'U1_E11_1_standing_1o3_UO0_1',
  'U1_E11_1_standing_1o3_UO120_0',
  'U1_E11_1_standing_1o3_UO120_1',
  'U1_E11_1_standing_1o3_UO150_0',
  'U1_E11_1_standing_1o3_UO150_1',
  'U1_E11_1_standing_1o3_UO180_0',
  'U1_E11_1_standing_1o3_UO180_1',
  'U1_E11_1_standing_1o3_UO30_1',
  'U1_E11_1_standing_1o3_UO60_0',
  'U1_E11_1_standing_1o3_UO60_1',
  'U1_E11_1_standing_1o3_UO90_0',
  'U1_E11_1_standing_1o3_UO90_1',

  'U0_E3_1_walking_1o0_WS-0_0',
  'U0_E3_1_walking_1o0_WS-1_0',
  'U0_E3_1_walking_1o0_WS-2_0',
  'U0_E3_1_walking_1o0_WS-3_0',


  'U0_E3_1_walking_1o0_HMG-CH_0',
  'U0_E3_1_walking_1o0_HMG-DH_0',
  'U0_E3_1_walking_1o0_HMG-M_0',
  'U0_E3_1_walking_1o0_C-C_0',
  'U0_E3_1_walking_1o0_C-D_0',
  'U0_E3_1_walking_1o0_C-T_0',
  'U0_E7_1_walking_1o0_C-S_0',
  'U0_E7_1_walking_1o0_C-S_1',

  'U0_E7_1_walking_1o0_IA-0_0',
  'U0_E7_1_walking_1o0_IA-0_1',
  'U0_E7_1_walking_1o0_IA-15_0',
  'U0_E7_1_walking_1o0_IA-15_1',
  'U0_E7_1_walking_1o0_IA-30_0',
  'U0_E7_1_walking_1o0_IA-45_1',
  'U1_E11_1_standing_1o3_IA-0_0',
  'U1_E11_1_standing_1o3_IA-15_0',
  'U1_E11_1_standing_1o3_IA-15_1',
  'U1_E11_1_standing_1o3_IA-30_0',
  'U1_E11_1_standing_1o3_IA-30_1',
  'U1_E11_1_standing_1o3_IA-45_2',

  'U0_E3_1_walking_1o0_AI-PC_0',
  'U0_E3_1_walking_1o0_AI-PT_0',
  'U0_E7_1_cooking_1o0_AI-CC_0',
  'U0_E7_1_cooking_1o0_AI-CC_1',
  'U0_E7_1_cooking_1o0_AI-CT_0',
  'U0_E7_1_cooking_1o0_AI-CT_1',
  'U0_E7_1_cooking_1o0_AI-CT_2',
  'U0_E7_1_cooking_1o0_AI-CT_3',
  'U0_E7_1_cooking_1o0_AI-CT_4',
  'U0_E7_1_walking_1o0_AI-F_0',
  'U0_E7_1_walking_1o0_AI-F_1',

  'U0o2_E2_2_walking_1o3_none_1',
  'U0o1o2_E2_3_walking_1o3_none_0',
  'U0o1_E2_2_walking_1o3_none_1',
  'U0o1_E2_2_walking_1o3_none_0',
  'U1o2_E11_2_walking_1o3_none_0',
  'U1o2_E11_2_walking_1o3_none_1',
  'U1o2_E11_2_walking_1o3_none_2',
  'U1o2_E11_2_walking_1o3_none_3',
  'U1o2_E2_2_walking_1o3_none_2',
  'U1o2o3_E11_3_walking_1o3_none_1',
  'U1o2o3_E11_3_walking_1o3_none_2',
  'U1o2o3o6o10_E2_5_walking_1o3_none_2',
  'U1o2o3o6o7o10_E11_6_walking_1o3_none_3',
  'U1o2o3o7_E11_4_walking_1o3_none_1',
  'U1o2o3o7_E11_4_walking_1o3_none_3',
  'U1o2o3o7o10_E11_5_walking_1o3_none_2',
  'U1o2o3o7o10_E11_5_walking_1o3_none_3',
  'U2o3_E2_2_walking_1o3_none_2',
  'U2o3o6o10_E2_4_walking_1o3_none_2',
  'none_E0_0_none_1o5_none_1',


  'x_E10_x_walking_1o0_none_30',
  'x_E10_x_walking_1o0_none_31',
  'x_E10_x_walking_1o0_none_32',
  'x_E10_x_walking_1o0_none_5',
  'x_E10_x_walking_1o0_none_37',
  'x_E6_x_walking_1o3_none_0',
  'x_E5_x_walking_0o8_none_19',
  'x_E8_x_walking_0o8_none_2',
  'x_E8_x_walking_0o8_none_3',
  'x_E8_x_walking_0o8_none_4',
  'x_E8_x_walking_0o8_none_5',
  'x_E8_x_walking_0o8_none_6',
  'x_E8_x_walking_0o8_none_7',
  'x_E8_x_walking_0o8_none_8',
  'x_E8_x_walking_0o8_none_9',
  'x_E8_x_walking_1o3_none_0',
  'x_E8_x_walking_1o3_none_1',
  'x_E8_x_walking_1o3_none_2',
  'x_E8_x_walking_1o3_none_3',
  'x_E8_x_walking_1o3_none_4',
  'x_E8_x_walking_1o3_none_6',
  'x_E8_x_walking_1o3_none_7',
  'x_E8_x_walking_1o3_none_8',
]